apiVersion: integration.ossm/v1alpha1
kind: Integration
metadata:
  name: my-integration
  namespace: istio-system
spec:
  istioRef:
    name: default
  metrics:
    type: ClusterObservability
    clusterObservability:
      monitoringStackRef:
        name: my-stack
        namespace: monitoring
